### ISSUE TITLE
Prettier filenames

### ISSUE THREAD

**Issue by klonos** [serundeputy/sql-dump-sanitize#7]
The scripts currently produce files in the form of:

backdropcmsorg-April-29-2018-30622-sanatized.sql.gz
files-April-29-2018-30001.tar.gz

I think that it would be best to have the filenames be:

backdropcmsorg-db-20180429-30622-sanatized.sql.gz
backdropcmsorg-files-20180429-30001.tar.gz

---

PR: https://github.com/serundeputy/sql-dump-sanitize/pull/8

**Comment by serundeputy** [comment]
@klonos since this is a user preference. I think we should make the file names configurable via the `config.ini` file.

**Comment by serundeputy** [comment]
i'm going to close this as wontfix since this is primarily a dev tool and gets the job done.

If someone has the time and gusto to make the filenames configureable w/ `config.ini` I would not reject a working, tested PR.
